# Generated by Django 3.0.4 on 2020-03-22 02:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('position', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pos',
            old_name='changed_time',
            new_name='changedTime',
        ),
        migrations.RenameField(
            model_name='pos',
            old_name='created_time',
            new_name='createdTime',
        ),
    ]
